[[plugins]]
package = "@netlify/plugin-gatsby"

[build.environment]
SECRETS_SCAN_OMIT_KEYS = "CONTENTFUL_SPACE_ID"

[functions]
  directory = "netlify/functions/"

[functions."stripeWebhook"]
  type = "raw"

[[redirects]]
  from = "/ordenadores-para-creadores-y-streamers/"
  to = "/ordenadores-creadores-streamers/"
  status = 301
  force = true

[[redirects]]
  from = "/terminos-y-condiciones/"
  to = "/condiciones-de-uso/"
  status = 301
  force = true

[[redirects]]
  from = "/politica-de-garantia/"
  to = "/condiciones-de-venta-y-garantia/"
  status = 301
  force = true

[[redirects]]
  from = "/ordenadores-ia/"
  to = "/ordenadores-inteligencia-artificial/"
  status = 301
  force = true

[[redirects]]
  from = "/ordenadores-para-creadores-streamers/"
  to = "/ordenadores-creadores-streamers/"
  status = 301
  force = true

[[redirects]]
  from = "/contact/"
  to = "/contacto/"
  status = 301
  force = true

[[redirects]]
  from = "/ordenadores-para-gaming/"
  to = "/ordenadores-gaming/"
  status = 301
  force = true

[[redirects]]
  from = "/ordenador/:slug"
  to = "/:slug"
  status = 301
  force = true

[[redirects]]
  from = "/google-review/"
  to = "https://search.google.com/local/writereview?placeid=ChIJO7XjxURPYA0RNw-aohrxZNg"
  status = 301
  force = true

[[redirects]]
  from = "/ordenador/ordenadores-gaming/powerstack/"
  to = "/ordenadores-gaming/powerstack/"
  status = 301
  force = true

[build]
  publish = "public"
  command = "gatsby build"

[dev]
  command = "gatsby develop" 
  
  targetPort = 8000 
  
  port = 9999 
  
  publish = "public"
  autoLaunch = false